### ISSUE TITLE
Sonar runner vs mvn sonar:sonar

### ISSUE THREAD

**Issue by RaviVaranasi** [sonar-intellij-plugin/sonar-intellij-plugin#100]
Use case 1:
As a developer, i want to run analysis locally in preview mode to verify that issues are fixed before committing my code. I would like the local analysis to run against the same rules configured on remote sonar server. My project is a multi-module java project build with maven.

Use case 2:
As a developer, i want to run analysis locally in incremental mode to make sure no new issues were introduced. I would like the local analysis to run against the same rules configured on remote sonar server. My project is a multi-module java project build with maven. I would like issues in intellij and also fail 'mvn clean install' build in case new issues were introduced.

My questions  are -

1. Is it better to use sonar-runner or mvn sonar:sonar plugin? Are there any tradeoffs ?
2. Is the best way to implement this is to write a shell script and invoke it from the sonar intellij plugin?
3. How to make the maven build fail when new issues are introduced ?

```
/Users/tools/sonar-runner-2.4/bin/sonar-runner -Dsonar.analysis.mode=incremental -Dsonar.issuesReport.html.enable=true  -Dsonar.host.url=http://dfwsonas1/ -Dsonar.login=user
-Dsonar.password=password -Dsonar.projectKey=com.organization.project:parent_module_name
```
I tried looking at existing issues, but did not find a solution.

Thanks in advance,
Ravi

**Comment by omayevskiy** [comment]
hello, also if your questions are not directly connected to the plugin, but the plugin is part of sonar integration, here some ideas:

1. Is it better to use sonar-runner or mvn sonar:sonar plugin? Are there any tradeoffs ?
As you have a project built by mvn, it will be simpler with mvn sonar:sonar. Under the hood the sonar mvn plugin  does nothing else then calling sonar-runner, but auto configure path, language and so on for you. Nevertheless you can use sonar-runner if you want total control over sonar execution.

2. Is the best way to implement this is to write a shell script and invoke it from the sonar intellij plugin?
This is how I do it. In simplest case it is enough to enter the mvn sonar:sonar command directly, but in more extended scenarios it is better to have a little script.

3. How to make the maven build fail when new issues are introduced ?
The plugin won't be able to show any issues, if you break the build. Breaking the build is more useful  for jenkins execution + [sonar issues plugin](http://docs.sonarqube.org/display/SONAR/Issues+Report+Plugin). Take a look at [sonar build breaker plugin](http://docs.codehaus.org/display/SONAR/Build+Breaker+Plugin) if you want to break the build.

**Comment by RaviVaranasi** [comment]
Thanks @omayevskiy for your answer. Appreciate you taking time to answer.

**Comment by IevgenRagulin** [comment]
3. How to make the maven build fail when new issues are introduced ?
The answer from @omayevskiy has mislead me a little bit, and I thought that it's impossible to break the build locally if new issues are introduced. However, it's possible. You can associate a quality gate with a project which would not let you introduce new issues. Then, with a help of a build breaker plugin, you could configure you build to break. With a help of issues report plugin, you can configure maven to generate an html report on your issues.

**Comment by omayevskiy** [comment]
@IevgenRagulin right, but it's bad for the plugin, as it will not show new issues in intellij, but you can have two scripts, one for plugin, one for console execution ;)
