### ISSUE TITLE
Fetching SonarQube resources crashes on Intellij Idea 14 (both Ultimate and Community edition)

### ISSUE THREAD

**Issue by babbupandey** [sonar-intellij-plugin/sonar-intellij-plugin#102]
![screen shot 2015-01-12 at 9 12 29 pm](https://cloud.githubusercontent.com/assets/3735997/5716274/c81d72dc-9a9f-11e4-9554-e0dd402a28af.png)

**Comment by omayevskiy** [comment]
looks like you cannot connect to your server

**Comment by babbupandey** [comment]
I cannot, but when I use it on 13.1 then it works without any problem

**Comment by omayevskiy** [comment]
it worked also with 14.0.0 seems to be an issue with the newest 14.0.2

**Comment by omayevskiy** [comment]
ok it looks like the sonar server settings are getting lost, the sonar server name is still saved but not the underlying hostname settings.

to fix the issue in IDEA 14.0.2:

Other Settings -> SonarQube
Sonar server "your_server" -> remove
Sonar server -> add
Apply

Should work again

**Comment by babbupandey** [comment]
I am sorry but I still get the same issue when I try to download the resources. Just to make sure I did it correctly, I removed my server and added it back and then tried to download the resources, is this correct?

**Comment by omayevskiy** [comment]
yes, what I also did is recreating the server under a different name and then rename it to the old one.

**Comment by babbupandey** [comment]
The problem was that in my IntelliJ I hadn't selected the option to accept all server certificates. As soon as I selected that, it worked like a charm.
