### ISSUE TITLE
SonarQube new issue analyze doesn't find suspicious code

### ISSUE THREAD

**Issue by smsnheck** [sonar-intellij-plugin/sonar-intellij-plugin#103]
Hi there, 

i've installed your plugin and configured it the way you described in the readme.md. When i ran the Analyze > Inspect Code with a custom inspection profile (only new issues) the output tells me

> Reading issues from ****/target/sonar/sonar-report.json
> Found 21 issues in the SonarQube report
> INFO 13:04:23.209 > Creating index from SonarQube report
> INFO 13:04:23.209 > Start processing 199 files and 21 issues with 8 threads
> INFO 13:04:23.210 > 179 / 199 files processed
> INFO 13:04:23.212 > Finished creating index from SonarQube report with 1 issues in 00:00:002

but the popup tells me that no suspicious code was found (but for testing purposes i wrote a method with 4 nested for-loops). But there is an entry in the json file for "too deeply nested loops". 

Any ideas why the issue is not reported?

**Comment by omayevskiy** [comment]
> When i ran the Analyze > Inspect Code with a custom inspection profile (only new issues) the output tells me

if your analysis scope does not contain the file with the issues, you will not see them, also if they are found in the report.

Btw. for analysis of only new issues you don't need to create a profile, it is enough to run inspection by name.

**Comment by smsnheck** [comment]
Closing due to wrong configuration settings. I added authentication parameters when adding the sonar server, and didn't activate the checkbox "anonymous". Now it's working!
