### ISSUE TITLE
Annotations in PHPStorm shown twice per File

### ISSUE THREAD

**Issue by CyberLine** [sonar-intellij-plugin/sonar-intellij-plugin#106]
Now that annotations are shown both in PHPStorm > 7 and 8, they are shown twice per file.

![bildschirmfoto 2015-01-21 um 00 02 11](https://cloud.githubusercontent.com/assets/195617/5828111/dba0179e-a100-11e4-9bc2-51d7adc1102a.png)

**Comment by omayevskiy** [comment]
can you show little more context
is it twice in editor?
is it twice in inspection window?

**Comment by CyberLine** [comment]
Twice in Editor only.

omayevskiy <notifications@github.com> schrieb am Mi., 21. Jan. 2015 00:07:

**Comment by omayevskiy** [comment]
of some reason in phpstorm a php file is annotated once as php once as html file
built in a fix for this, try the snapshot.
I did not check what happens for js or html files.

**Comment by omayevskiy** [comment]
call for feedback

**Comment by CyberLine** [comment]
Works both for 7.1 and 8.0.
