### ISSUE TITLE
https

### ISSUE THREAD

**Issue by kpbochenek** [sonar-intellij-plugin/sonar-intellij-plugin#108]
Https urls are not supported?

Is there any workaround for now?

**Comment by omayevskiy** [comment]
they are, nope no workarounds
you need to handle ssl certificates on intellij/jvm level

**Comment by kpbochenek** [comment]
Oh that's great :)

By any chance do you know how to configure this?

**Comment by omayevskiy** [comment]
In my case I needed just to click on the "Accept" button once ;-P
Another case could be something like:
```
sudo $JAVA_HOME/bin/keytool -importcert -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit -file $f -alias $f -noprompt
```
but it really depends and out of the scope

**Comment by kpbochenek** [comment]
Okay you are totally right, I followed this:
https://confluence.jetbrains.com/display/TCD8/Using+HTTPS+to+access+TeamCity+server#UsingHTTPStoaccessTeamCityserver-JVMConfiguration

And it worked like a charm :)
