### ISSUE TITLE
If condition is covered only once (not in all logical combinations), the line is shown green in IntelliJ, but not in the SonarQube GUI.

### ISSUE THREAD

**Issue by eichench** [sonar-intellij-plugin/sonar-intellij-plugin#111]
If a condition run through only in one logical setting, the SonarQube GUI shows the line with an orange label (line 46):
![coverage sonar cropped](https://cloud.githubusercontent.com/assets/6887432/5920399/950fa6dc-a63c-11e4-86e6-b9d657843feb.png)
On the other, the sonar-intellij-plugin shows the line as green (same line 46):
![coverage intellij cropped](https://cloud.githubusercontent.com/assets/6887432/5920398/94fa5a98-a63c-11e4-859d-5d97ecd8f386.png)
This is rather confusing. The line should be labelled with a warning in the same way as in the SonarQube GUI.

**Comment by omayevskiy** [comment]
the plugin does not handle test coverage data, only sonar issues
the green line you mentioned comes from intellij's own test coverage tools.

**Comment by omayevskiy** [comment]
PS: you have german code :-P

**Comment by eichench** [comment]
@omayevskiy  Thanks anyway for your reply. The code is plain Java, actually :-) Of course, you're right: technical terms are German, yes. Well spotted :-)
