### ISSUE TITLE
no details for test coverage code issue

### ISSUE THREAD

**Issue by gesines** [sonar-intellij-plugin/sonar-intellij-plugin#116]
When test coverage issues have been identified by sonar they are reported to idea without informations regarding coverage details (i.e. uncovered lines). So developers need to refer to the sonar server for details of this issue, which is quite unhandy.

**Comment by omayevskiy** [comment]
test coverage data is currently not supported and currently also not planned to support it (maybe in v3 ;-) )

**Comment by AAverin** [comment]
Would like to raise this issue again.
We use Sonarqube for Android and have Jacoco code coverage implemented, properly displaying on Sonarqube server. Android Studio also supports Jacoco, but for some reason coverage is not correct.
I was hoping to use your Sonarqube plugin to somehow display coverage sonarqube knows about directly in Android Studio.
Do you think it's possible?

**Comment by omayevskiy** [comment]
The built in functionality from intellij works fine for me, it's still not planned from my side. Fill free to contribute.

**Comment by AAverin** [comment]
Works for me too, but it doesn't read coverage from sonarqube.

**Comment by omayevskiy** [comment]
Sure you also want the current coverage state and not outdated one from sonar, what would you need coverage from sonar for?

**Comment by AAverin** [comment]
I don't really know where IntelliJ grabs coverage from.
To sonar work with Android we have a customised configuration that most likely moves report files to some other then default location. Maybe if I keep a default copy coverage will work properly, I'll need to check.

My idea was to get exactly same coverage status as on Sonarqube dashboard. That would be re-using same jacoco reports that are used by Sonarqube to display coverage within Android Studio.

**Comment by omayevskiy** [comment]
Analyze -> Show coverage data -> try to import you jacoco.exec (no warranty)
Normally I just ran my tests with coverage and select Jacoco as test coverage runner.

**Comment by AAverin** [comment]
In my case when I do that - coverage remains at 0 instead of 95%, even though sonarqube reports everything correctly.

**Comment by omayevskiy** [comment]
sound like something worse to create an intellij issue in dev forum, import of jacoco data should work.
