### ISSUE TITLE
Support Local Analysis without downloading server issues

### ISSUE THREAD

**Issue by tpischke** [sonar-intellij-plugin/sonar-intellij-plugin#118]
At the moment, server issues for all modules are downloaded, even when I only want to perform local analysis on the current file.  

Ideally, only the quality profile would be downloaded, not the server issues.   Furthermore, it doesn't make sense to download server issues for all modules, when only the current file is being analyzed.

**Comment by omayevskiy** [comment]
to run local analysis only start analysis for the  " SonarQube Issue (new issues)" only:
Analyze -> Run Inspection by Name

>Furthermore, it doesn't make sense to download server issues for all modules, when only the current file is being analyzed

so don't do this, it depends on how you run the analysis and your configuration, but you cannot omit running a local analysis for an entire module at the moment, as sonar api does not support that kind of analysis for one file only.
