### ISSUE TITLE
Issues not found by plugin.

### ISSUE THREAD

**Issue by radfahrer** [sonar-intellij-plugin/sonar-intellij-plugin#120]
When I run the analysis I get both:

    INFO 15:56:44.460 > -------------  Issues Report  -------------
    INFO 15:56:44.460 > 
    INFO 15:56:44.460 >         +2 issues
    INFO 15:56:44.460 > 
    INFO 15:56:44.460 >         +2 critical
    INFO 15:56:44.460 > 
    INFO 15:56:44.460 > -------------------------------------------

and: 

    3:57:01 PM SonarQube: No new SonarQube issues
    3:57:01 PM No suspicious code found

what gives?

**Comment by omayevskiy** [comment]
>When I run the analysis I get both:
how do you run it?

>3:57:01 PM SonarQube: No new SonarQube issues
>3:57:01 PM No suspicious code found

how do you run in?

you can check what is inside the sonar-report.json manually.

**Comment by radfahrer** [comment]
`mvn clean compile sonar:sonar -DskipTests=true
-Dsonar.login=$SONAR_USER_NAME -Dsonar.password=$SONAR_USER_PASSWORD` is
the command, and the two issues are in the sonar-report.json. The plugin
seems to be missing them.

**Comment by omayevskiy** [comment]
how did you configure the path to sonar-report.json?

**Comment by radfahrer** [comment]
I ran the command mentioned above manually, and then browsed to the
generated spmar-report.json file.

--
Dan

**Comment by omayevskiy** [comment]
there are few more options what could be wrong with your configuration:

working directory
the configured sonar resource
multi module misunderstanding
sonar branching support and sonar 5.x (does not work)

**Comment by radfahrer** [comment]
On Tue, Feb 17, 2015 at 5:40 AM, omayevskiy <notifications@github.com>
wrote:

> there are few more options what could be wrong with your configuration:
>
> working directory
>
If the working directory is wrong how am I getting correct output from mvn?

> the configured sonar resource
>
Rules are downloading, and running, and I'm getting the expected response
on the command line.

> multi module misunderstanding
>
Please elaborate, what is a multi module misunderstanding and how do I fix
it?

> sonar branching support and sonar 5.x (does not work)
>
Running Version 4.5.1

**Comment by omayevskiy** [comment]
>If the working directory is wrong how am I getting correct output from mvn?
e.g. you execute mvn command on parent pom level, but not in the plugin.

>Rules are downloading, and running, and I'm getting the expected response
on the command line.
The plugin does not download any rules, instead it runs "mvn command" and reads the sonar-report.json . This way you don't need to sync rules.
But to much the issues from the report to src files in idea project, you need to specify the sonar resources for each module correctly.
>Please elaborate, what is a multi module misunderstanding and how do I fix
it?
Did you read the readme?

**Comment by danprince1** [comment]
I'm having this problem too, and I think I have project and modules configured correctly according to the readme.  But I am using SonarQube server version 5.1.  Is it true that the plugin does not support this sonar version, as hinted at in [this comment](https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/issues/120#issuecomment-74668790)?  It would be helpful to state in the readme which versions the plugin in compatible with.
