### ISSUE TITLE
No Inline Inspections Displayed in IntelliJ 14.1

### ISSUE THREAD

**Issue by Vile2539** [sonar-intellij-plugin/sonar-intellij-plugin#123]
Hi,

I'm having an issue with IntelliJ 14.1, and displaying the results of the SonarQube code inspection inline in the editor window. I believe I have everything set up correctly, and the issues are actually displaying in the code inspection window. 

Settings window:
![sonarqube settings](https://cloud.githubusercontent.com/assets/4079022/6846496/cd6f9abc-d3b6-11e4-84ec-75272283d54e.jpg)

Configuration for multi-modules in Project Structure:
![project structure](https://cloud.githubusercontent.com/assets/4079022/6846512/e0dbfbcc-d3b6-11e4-8e31-1cef38fbdebd.jpg)

Issues showing up after inspection for each configured module:
![issues](https://cloud.githubusercontent.com/assets/4079022/6846523/f4db78d2-d3b6-11e4-9339-0e7358851ae0.jpg)

Inspection window for a single class, showing multiple issues:
![inspection window](https://cloud.githubusercontent.com/assets/4079022/6846561/122f8072-d3b7-11e4-83d7-74d7a058bce8.jpg)

Editor window for the same class, showing no inline warnings/errors:
![no inline inspections](https://cloud.githubusercontent.com/assets/4079022/6846582/267b054c-d3b7-11e4-9b14-96136a83b3ec.jpg)

It's quite possible that I have not configured something correctly, but I find it strange that the issues are actually showing up in the inspection window for each module correctly, and that inspection window does correctly link to the file.

Any advice on this would be appreciated, especially if I'm just missing something simple.

Thanks.

**Comment by omayevskiy** [comment]
Same issue for me with intellij 14.1, they changed something with markings, need to look at it :-)

**Comment by Vile2539** [comment]
Thanks for the extremely quick response. Glad I'm not just going crazy :)

**Comment by omayevskiy** [comment]
don't have a fix yet, after first look, the annotations a still created correctly and contains the needed data, but they are simply not displayed by intellij any more... to be continued...

**Comment by Vile2539** [comment]
I've noticed a few times that they'll actually pop up for a couple of seconds. I haven't found any rhyme or reason as to when though, and they quickly disappear.
