### ISSUE TITLE
Support for Javascript

### ISSUE THREAD

**Issue by yorraksahb** [sonar-intellij-plugin/sonar-intellij-plugin#129]
Does this plugin supports JavaScript as well? I am using Webstorm v9 and when i integrate the Soanrcube plugin, i don't see the analyze menu. But for IntelliJ it do come.

**Comment by omayevskiy** [comment]
>Does this plugin supports JavaScript as well
the plugin supports any language

>I am using Webstorm v9 and when i integrate the Soanrcube plugin, i don't see the analyze menu.
the menu in webstorm is different, if you know how to run inspections, sonar will work for you as well.
