### ISSUE TITLE
Issue with SonarQube detecting new issues (SonarQube versions 4.5.5 vs 5.0.1+)

### ISSUE THREAD

**Issue by benpick** [sonar-intellij-plugin/sonar-intellij-plugin#130]
Hello,

In working with the intellij plugin for phpstorm 9.0.1, I have encountered a problem. The tool works without issues and errors in analyzing source code files and projects. However, in generating and displaying the results, when sending the code to versions of SonarQube 5.0.1+, every issue is identified as a new issue. 

I have tried performing the analysis with a variety of configurations, settings, and versions. The only difference between successful usage of the intellij plugin is the version of sonarqube. Is this a documented issue? Is there a way to overcome the problem?

I would prefer to find a solution other than downgrading to a previous version of SonarQube as that will be a large work effort and likely break other existing functionality within the environment. 

I have attached 2 screenshots to further explain this situation. Note that the successful instance shows new issues in the results. In the failure screenshot, all of the identified issues are listed as new issues. 

![output_failure_5 0 1](https://cloud.githubusercontent.com/assets/12281003/9338821/c1648a8c-45b4-11e5-99b9-b7743a660fe2.JPG)
![output_success_4 5 5](https://cloud.githubusercontent.com/assets/12281003/9338822/c16795a6-45b4-11e5-98cc-5ef0d7fdc2e2.JPG)

Any suggestions or troubleshooting steps? 

Thanks.

- Ben

**Comment by omayevskiy** [comment]
probably if you run the analysis against the newer version, it does not have any persisted results yet, thus all issues are new.

**Comment by benpick** [comment]
No. Every time analysis is performed with the new version, the results are considered to be new. Even when executed in succession. 
Any ideas why that may occur? 
Running the same tests in 4.5.5 behave in the expected manner in which the first scan all of the results are considered new in the SonarQube (new issues) group, then subsequent tests move the findings to the SonarQube group. 
No matter how many times I run run the tests with SonarQube versions 5.0.1+ the results are considered to be new. I have replicated these bad results using SonarQube 5.0.1 and the latest 5.1.2.

Any ideas on troubleshooting or resolving the issue?

Thanks.

**Comment by benpick** [comment]
The problem was solved. The source code stored in SonarQube had multiple repositories. Newer code was placed into a separate repository so it was considered to be new. By changing the references and source code locations the output is displaying as expected. 

Thanks.

**Comment by omayevskiy** [comment]
thx for posting the solution
