### ISSUE TITLE
First Time Analysis - Resource Not Listed

### ISSUE THREAD

**Issue by berenerchamion** [sonar-intellij-plugin/sonar-intellij-plugin#134]
Hello,

I'm trying to analyze an android project using Android Studio. I've provisioned a project in the server console, but it does nto show up in teh download resource list in the Studio configuration. Do I need to run at least one analysis server-side before I can do this in studio?

I do see other projects listed in the download list, but not my android one. 

I'm running SQ 5.1 and the latest Android Studio.

**Comment by omayevskiy** [comment]
yes yo need to be able to see it under project list
