### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by allanffg** [sonar-intellij-plugin/sonar-intellij-plugin#135]
Trying to install the plugin from the intellij repo and from disk.
After the restart to activate the plugin never appears in my settings and disappears from plugin list.

Using intellij 14.5 Community.

**Comment by omayevskiy** [comment]
works for me with intellij 15

**Comment by allanffg** [comment]
Was able to install for Community Edition 15. But not for Ultimate 15 - is this supported?

**Comment by omayevskiy** [comment]
I am using Ultimate, works for me
