### ISSUE TITLE
Unable to save password in IntelliJ password database

### ISSUE THREAD

**Issue by speechkey** [sonar-intellij-plugin/sonar-intellij-plugin#138]
I'm unable to save password for SonarQube server in IntelliJ Settings > Other Settings > SonarQube in IntelliJ 14.1. On save the dialog gets hidden but the password get lost.

**Comment by omayevskiy** [comment]
I cannot reproduce it. I can enter the pw, restart intellij and settings are still there.
Are you sure you unchecked the anonymous checkbox?
