### ISSUE TITLE
How do I see new issues?

### ISSUE THREAD

**Issue by ehmkah** [sonar-intellij-plugin/sonar-intellij-plugin#140]
After configuring the plugin it downloads the sonar violations from the server and displays them correctly in sonarCube item in inspection result.

If I make a local analyse with the way you described  a sonar.report file is generated successfully. It contains several issues with status="ADDED". But when I look into the inspection profile I still only see the issues downloaded from central sonar report. What am I doing wrong and where do i find the new issues?

i am using version 2.0.11 and intellij 15.

**Comment by omayevskiy** [comment]
What is the output from SonarQube console?

**Comment by ehmkah** [comment]
last lines look like:
INFO 11:05:15.828 > finished with exit code 0 in 01:30:711
INFO 11:05:15.828 > Reading issues from D:/rep/example-project/target/sonar/sonar-report.json
INFO 11:05:15.829 > Found 30 issues in the SonarQube report
INFO 11:05:15.829 > Creating index from SonarQube report
INFO 11:05:15.829 > Start processing 287 files and 30 issues with 2 threads
INFO 11:05:15.836 > 89 / 287 files processed
INFO 11:05:15.838 > 267 / 287 files processed
INFO 11:05:15.839 > Finished creating index from SonarQube report with 0 issues in 00:00:010
INFO 11:05:15.839 > Creating index from SonarQube report
INFO 11:05:15.839 > Start processing 287 files and 30 issues with 2 threads
INFO 11:05:15.842 > 89 / 287 files processed
INFO 11:05:15.847 > 267 / 287 files processed
INFO 11:05:15.849 > Finished creating index from SonarQube report with 0 issues in 00:00:010
INFO 11:05:15.850 > Creating index from SonarQube report
INFO 11:05:15.850 > Start processing 287 files and 30 issues with 2 threads
INFO 11:05:15.853 > 89 / 287 files processed
INFO 11:05:15.866 > 267 / 287 files processed
INFO 11:05:15.869 > Finished creating index from SonarQube report with 0 issues in 00:00:019
INFO 11:05:15.870 > Creating index from SonarQube report
INFO 11:05:15.870 > Start processing 287 files and 30 issues with 2 threads
INFO 11:05:15.872 > 89 / 287 files processed
INFO 11:05:15.874 > 267 / 287 files processed
INFO 11:05:15.875 > Finished creating index from SonarQube report with 0 issues in 00:00:005
INFO 11:05:15.877 > Creating index from SonarQube report
INFO 11:05:15.877 > Start processing 287 files and 30 issues with 2 threads
INFO 11:05:15.879 > 89 / 287 files processed
INFO 11:05:15.881 > 267 / 287 files processed
INFO 11:05:15.881 > Finished creating index from SonarQube report with 0 issues in 00:00:004
INFO 11:05:15.882 > Creating index from SonarQube report
INFO 11:05:15.882 > Start processing 287 files and 30 issues with 2 threads
INFO 11:05:15.885 > 89 / 287 files processed
INFO 11:05:15.890 > 267 / 287 files processed
INFO 11:05:15.890 > Finished creating index from SonarQube report with 0 issues in 00:00:008
INFO 11:05:15.892 > Creating index from SonarQube report
INFO 11:05:15.892 > Start processing 287 files and 30 issues with 2 threads
INFO 11:05:15.893 > 89 / 287 files processed
INFO 11:05:15.896 > 267 / 287 files processed
INFO 11:05:15.897 > Finished creating index from SonarQube report with 0 issues in 00:00:00

**Comment by omayevskiy** [comment]
looks like you have a multi maven project? Did you configured each intellij modul with sonar settings?

**Comment by ehmkah** [comment]
yes - i forgot it but now they are configured. Some modules are not analysed on sonar because they contain only generated code, so I can not link them to sonar. Results did not change. :-(

**Comment by omayevskiy** [comment]
you should analyze single modules and not entire project. You also don't need to configure everything, only what you work with.

**Comment by ehmkah** [comment]
If I do that then then number of issues reduces (because only those module is analysed). For me it looks like that the report file is ignored completly. Any ideas how I could check that is used?

**Comment by omayevskiy** [comment]
you see it in console:

INFO 11:05:15.828 > Reading issues from D:/rep/example-project/target/sonar/sonar-report.json

if you have a multi maven modul this path maybe wrong, because you have also:
example-project/module1/target/sonar/sonar-report.json
example-project/module2/target/sonar/sonar-report.json
