### ISSUE TITLE
How can I debug the plugin

### ISSUE THREAD

**Issue by ehmkah** [sonar-intellij-plugin/sonar-intellij-plugin#141]
I do not know what I have to do to start debugging the plugin. The first (and only) idea plugin I worked on had an iml file which I opened and was then able to run the plugin in debug mode in a new intelliJ instance. How do I achieve it with sonar-intellij-plugin?

**Comment by omayevskiy** [comment]
run gradle idea
this will generate the .iml file

**Comment by ehmkah** [comment]
okay, that works! thank you
