### ISSUE TITLE
What could be a reason that the plugin does not start in debug mode

### ISSUE THREAD

**Issue by ehmkah** [sonar-intellij-plugin/sonar-intellij-plugin#143]
I tried to play a little bit around with the plugin. After creating the intelliJ project files I opened the directory and configured the SDK and run the plugin. 

Unfortunately the plugin does not appear in the "debug" intellij? What do I have to change to make it work? I am using Linux, Intellij 15 Community Edition, JDK 8 (Oracle), and master branch.

By the way: What is the option -XX:+UseCompressedOops for? It crashes my (linux) openjdk-7 and jdk8? I commented it out,  created the intellij project and "debug" intellij starts (but without the plugin as described above).

**Comment by omayevskiy** [comment]
Did you configure the SDK to Intellij Plugin SDK? Just java SDK ist not enough it must be Intellij Plugin SDK

**Comment by ehmkah** [comment]
Yes that was what I did. Otherwise it is not possible to start the plugin inside of Intellij. The same SDK works fine if I create a simple Intellij Plugin (without anything) so I think it is configured correctly.

**Comment by omayevskiy** [comment]
btw. in one of the last pull requests @bdbogjoe made it possible to run the plugin with gradle:

<code>
gradle runIdea
</code>

I also configured an Intellij gradle task you can run in debug or run modus.

**Comment by ehmkah** [comment]
The gradle tasak works! Thank you!

Do you think its worth documenting a small "howto develop"? Should I add the two hints you gave me to the Readme.md? Or what be a useful name for the document for you? develop.md?

**Comment by omayevskiy** [comment]
I think a small "howto develop" in the README.md would be great.

**Comment by ehmkah** [comment]
okay - i see what I could do ;-)
