### ISSUE TITLE
500 error downloading resources due to multiple conflicting ruby versions.

### ISSUE THREAD

**Issue by dvictorB** [sonar-intellij-plugin/sonar-intellij-plugin#147]
Logging this in case others come across it.  It's not a bug, just FYI.  Seen with Sonarqube 5.2 plugin 2.0.11 with IDEA 15.0.2 Mac OSX but is a known issue with Sonarqube.  Fetching resources results in a 500 from Sonar and a backtrace in the plugin as below.

![sqerror](https://cloud.githubusercontent.com/assets/578600/12048978/9318b21e-aed9-11e5-8fd4-269777082912.png)

This was the error in logs/sonar.log

    2015.12.22 15:39:05 ERROR web[o.s.s.ui.JRubyFacade] Fail to render:    
    http://localhost:9000/api/resources/search?...
    undefined method `generate' for #<JSON::Ext::Generator::State:0x3d96e2e2>
        /Users/.../.rvm/gems/ruby-2.0.0-p195/gems/json-1.8.0/lib/json/common.rb:223:in `generate'

I had an ancient 'rvm' install with an different version of ruby kicking around 

    $ ruby --version
    ruby 2.0.0p195 (2013-05-14 revision 40734) [x86_64-darwin12.3.0]

Sonarqube includes a bundled ruby 1.9.3 it appears via jruby 1.7.9 (http://jruby.org/2013/12/06/jruby-1-7-9.html)

     sonarqube-5.2]$ ls lib/server/jruby-complete-*
     lib/server/jruby-complete-1.7.9.jar

When I removed the 'rvm' entry from my command line search path then it all worked fine.

    #commented out this line in .profile
    #[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

**Comment by omayevskiy** [comment]
thx for sharing
