### ISSUE TITLE
Error: JAVA_HOME is not defined correctly

### ISSUE THREAD

**Issue by davotoula** [sonar-intellij-plugin/sonar-intellij-plugin#148]
I've removed my local Java 6 installation and am now getting the above error. Details:

```
Error: JAVA_HOME is not defined correctly.
We cannot execute /System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/bin/java
```

My system has JAVA_HOME is set correctly:
```
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home
```

I'd rather not use a custom execution script, is there somewhere else I can define JAVA_HOME for the sonarqube plugin execution?

thanks

**Comment by omayevskiy** [comment]
first search result for Error: JAVA_HOME is not defined correctly :
http://stackoverflow.com/questions/27319495/error-java-home-is-not-defined-correctly-executing-maven

**Comment by davotoula** [comment]
My system has JAVA_HOME set correctly (via .bash_profile):
```Bash
echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home
```

I'm not sure from where the plugin is getting the old 
```
/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/bin/java

**Comment by omayevskiy** [comment]
The "system" JAVA_HOME is read by bash scripts, but if you run a mvn process it's more low level and does not run in a bash console. The old property could come from mvn properties.

**Comment by davotoula** [comment]
Thank your for the suggestions. I did 2 changes and the issues is now gone but I can't tell which one fixed it:

* Install latest maven and change M2_HOME
* Change maven in intellij to "bundled 3.x"

feel free to close
