### ISSUE TITLE
json report is not generated

### ISSUE THREAD

**Issue by Sendami** [sonar-intellij-plugin/sonar-intellij-plugin#149]
I'm using the following command line mvn -DskipTests -Dsonar.issuesReport.console.enable=true -Dsonar.issuesReport.html.enable=true -Dsonar.issuesReport.json.enable=true  -Dsonar.analysis.mode=preview sonar:sonar but the json report is not generated. The only report I'm able to generate is html one. Intellij needs this json report

**Comment by omayevskiy** [comment]
Check the output of your maven build.
Nevertheless here is an example of a working command line:    
     
    mvn clean install sonar:sonar
    -DskipTests=true 
    -Djava.awt.headless=true 
    -Dsonar.language=java 
    -Dsonar.analysis.mode=incremental 
    -Dsonar.host.url=http://localhost:9000

**Comment by aselamal** [comment]
I'm also having this problem, and can't integrate local analysis into the IDE via the plugin.

Things have changed in the new version of sonar. Does the plugin need to be updated to support v5.2?

`
ERROR: Invalid analysis mode: incremental. This mode was removed in SonarQube 5.2. Valid modes are: [preview, publish, issues]`

**Comment by isadovskiy** [comment]
It seems like the latest sonar does not support "incremental" mode and "preview" mode, which is supposed to be the replacement for, generates reports just in HTML format. Does anybody know if it's still possible to produce reports in JSON format?

**Comment by omayevskiy** [comment]
sonarqube moved the issues report plugin into main contribution.
the sonar.issuesReport.json.enable property is replaced by sonar.report.export.path

example:

    mvn -Dsonar.analysis.mode=preview -Dsonar.report.export.path=sonar-report.json clean install sonar:sonar

output:

    [INFO] [20:28:52.150] Export issues to /path/to/SonarSource-sonar-examples-0d445da/projects/languages/java/maven/java-maven-simple/target/sonar/sonar-report.json
