### ISSUE TITLE
Plugin ignores sonar.exclusions

### ISSUE THREAD

**Issue by Krakabek** [sonar-intellij-plugin/sonar-intellij-plugin#152]
My sonar-project.properties has this lines:

```
sonar.sources=src
sonar.exclusions=src/assets/**,src/tests/**,src/vendors/**
```

But when I run Inspect Code, files from excluded folders are analysed like they are not excluded.

(When I run sonar-runner from terminal, everything is OK)

**Comment by parky128** [comment]
I am experiencing the same issue when I inspect code in WebStorm using this plugin. We have a Jenkins setup also, which has a build step to connect to our Sonar server and perform code analysis which happily ignores the exclusions list.

Anyone know of how to resolve this?

**Comment by omayevskiy** [comment]
please note that plugin does not run analysis by itself. It either downloads issues from server or it runs your local analysis script. The sonar-project.properties file is not read at all by the plugin, this will be used by the sonar runner.
