### ISSUE TITLE
Add Feature to filter rules by ruleid

### ISSUE THREAD

**Issue by elkfrawy-df** [sonar-intellij-plugin/sonar-intellij-plugin#156]
Most of times we want to fix issues rule by rule, yet there is no way to filter results by ruleid in the plugin.

**Comment by omayevskiy** [comment]
you can filter rules using built in basic text search inside the inspection results window

**Comment by omayevskiy** [comment]
![bildschirmfoto 2016-12-09 um 15 02 19](https://cloud.githubusercontent.com/assets/3081911/21051493/d16619ce-be20-11e6-890a-59d55d0f1aa7.png)
