### ISSUE TITLE
Support Sonar's "User Token" in addition of username+password

### ISSUE THREAD

**Issue by albinpoignot** [sonar-intellij-plugin/sonar-intellij-plugin#160]
To connect to a remote Sonar Server, you could provide your credentials (username + password). However, this credentials will transit over the network and are a security issue.

Sonar provides User Token which could be used and are not a security issue.

**Comment by edimarlnx** [comment]
+1

**Comment by misterfifi1** [comment]
+1

**Comment by hngl** [comment]
+1

**Comment by Namnodorel** [comment]
Yes, PLEASE! Tokens are so much better than username + password ^^

**Comment by bdbogjoe** [comment]
+1

**Comment by luis-botelho-pereira** [comment]
+2

**Comment by gdegani** [comment]
+1

**Comment by ddattee** [comment]
+1

**Comment by npoirey** [comment]
I'm on a project where I have no username/password (it uses autologin) and as such I can't connect to sonar server because my only option is via token. This feature is a must have I think.

**Comment by DaFont** [comment]
I can't connect to sonar without the token way, there aren't users in our sonarqube server.

**Comment by SidekickJohn** [comment]
any news on this one? just like the others, we're unable to use the plugin until tokens are supported....

**Comment by sunilkharat** [comment]
+1

**Comment by omayevskiy** [comment]
@SidekickJohn at the moment I don't have resources to implement this.
pull requests are welcome
