### ISSUE TITLE
Sonarqube results are not getting displayed under the inspections tab in Intellij Idea 2016.2

### ISSUE THREAD

**Issue by chopraakash91** [sonar-intellij-plugin/sonar-intellij-plugin#161]
I am using Intellij Idea 2016.2. I have installed Sonarqube Community plugin 2.1.0. After anaylzing the code , sonarqube results are not shown in the inspections tab. It used to work with previos Intellij versions.

**Comment by batya239** [comment]
Will be fixed in IntelliJ IDEA 2016.3 https://youtrack.jetbrains.com/issue/IDEA-162032
