### ISSUE TITLE
NullPointerException after viewing Sonar options in Project Structure

### ISSUE THREAD

**Issue by Stargator** [sonar-intellij-plugin/sonar-intellij-plugin#166]
Already had sonar plugin installed for weeks and had it configured. I wasn't using the plugin's inspection feature, but was viewing the Sonar options under Project Structure. Did not change any of the setting, permanently.

> Argument for @NotNull parameter 'sonarServerName' of org/intellij/sonar/configuration/ResourcesSelectionConfigurable.<init> must not be null

> Argument for @NotNull parameter 'sonarServerName' of org/intellij/sonar/configuration/ResourcesSelectionConfigurable.<init> must not be null
> java.lang.IllegalArgumentException: Argument for @NotNull parameter 'sonarServerName' of org/intellij/sonar/configuration/ResourcesSelectionConfigurable.<init> must not be null
> 	at org.intellij.sonar.configuration.ResourcesSelectionConfigurable.<init>(ResourcesSelectionConfigurable.java)
> 	at org.intellij.sonar.configuration.partials.SonarResourcesTableView$5.run(SonarResourcesTableView.java:77)
> 	at org.intellij.sonar.configuration.partials.SonarResourcesTableView$5.run(SonarResourcesTableView.java:71)
> 	at com.intellij.ui.ToolbarDecorator$2.doAdd(ToolbarDecorator.java:431)
> 	at com.intellij.ui.CommonActionsPanel$Buttons.performAction(CommonActionsPanel.java:72)
> 	at com.intellij.ui.CommonActionsPanel$MyActionButton.actionPerformed(CommonActionsPanel.java:263)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
> 	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:188)
> 	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:154)
> 	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:325)
> 	at java.awt.Component.processEvent(Component.java:6298)
> 	at java.awt.Container.processEvent(Container.java:2236)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2294)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2280)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> 	at java.awt.EventQueue$4.run(EventQueue.java:731)
> 	at java.awt.EventQueue$4.run(EventQueue.java:729)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
> 	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
> 	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
> 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
> 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
> 	at java.awt.Dialog.show(Dialog.java:1084)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:779)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:457)
> 	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1693)
> 	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1635)
> 	at com.intellij.openapi.options.ex.SingleConfigurableEditor.a(SingleConfigurableEditor.java:127)
> 	at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
> 	at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:294)
> 	at com.intellij.openapi.options.ex.SingleConfigurableEditor.show(SingleConfigurableEditor.java:127)
> 	at com.intellij.ide.actions.ShowStructureSettingsAction.showDialog(ShowStructureSettingsAction.java:51)
> 	at com.intellij.ide.actions.ShowStructureSettingsAction.actionPerformed(ShowStructureSettingsAction.java:41)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
> 	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
> 	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:159)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:213)
> 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:315)
> 	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:920)
> 	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:130)
> 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:295)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.a(ActionMenuItem.java:112)
> 	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
> 	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
> 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:116)
> 	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:126)
> 	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
> 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
> 	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
> 	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
> 	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
> 	at java.awt.Component.processMouseEvent(Component.java:6533)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
> 	at java.awt.Component.processEvent(Component.java:6298)
> 	at java.awt.Container.processEvent(Container.java:2236)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2294)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2280)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> 	at java.awt.EventQueue$4.run(EventQueue.java:731)
> 	at java.awt.EventQueue$4.run(EventQueue.java:729)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
> 	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by omayevskiy** [comment]
please try newest version
https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/releases/tag/2.1.1-SNAPSHOT

**Comment by Stargator** [comment]
@omayevskiy Will try it out today and let you know

**Comment by Stargator** [comment]
I no longer see the error. So I would say it's resolved. But my local sonarqube setup has somehow reset to default. Projects and users I setup within SonarQube seem to be gone. Somehow, my local SonarQube has reverted to use the embedded database it came with.

I say that because while I do not see the error currently, I don't know if that will change once I restore my SonarQube instance.

If I do encounter the error again, I'll update this issue, but it will likely be a couple of weeks before I can turn my attention to setting up SonarQube again.
