### ISSUE TITLE
Only scope options: "current file" and "opened files"

### ISSUE THREAD

**Issue by acurvers** [sonar-intellij-plugin/sonar-intellij-plugin#176]
I have sonarlint IntelliJ plugin version Version: 2.4.3.1360

the Only scope options I have are: "current file" and "opened files"
is that a bug? I don't see any way to configure it so I have broader scope options

(I am not using a server binding at this moment.)

Looking forward to your feedback I would really like to start using this great plugin.

Thanks

**Comment by acurvers** [comment]
did anyone read this?

**Comment by acurvers** [comment]
@omayevskiy

**Comment by omayevskiy** [comment]
> I have sonarlint IntelliJ plugin version Version: 2.4.3.1360
Please post issues with sonarlint to https://github.com/SonarSource/sonarlint-intellij
