### ISSUE TITLE
Projects not downloaded from server

### ISSUE THREAD

**Issue by javixeneize** [sonar-intellij-plugin/sonar-intellij-plugin#184]
Hi

I am comparing this plugin with sonarlint and i am having some problems to make it work

Using Sonarlint, i can download all the projects from the sonar server and bind my local project to one of them

Using this plugin, i have configured the server, and, when selecting  the resource, no resources are downloaded.

Its similar to what is reported in #175 i think

Any help?

Thanks

**Comment by omayevskiy** [comment]
closing: duplicate of #179
