### ISSUE TITLE
PyCharm (and probably others IDEA IDEs) 2017.3 support

### ISSUE THREAD

**Issue by Epithumia** [sonar-intellij-plugin/sonar-intellij-plugin#190]
PyCharm 2017.3 rolled out and the plugin descriptor marks it as incompatible, forcing the IDE to roll back to 2.1.0, effectively breaking the sonarqube plugin.

If there weren't any breaking changes between 2017.2 and .3, a bump in the build compatibility range would be nice.

**Comment by jameslkey** [comment]
Back to the same inability to download resources...

**Comment by tiagomestreteixeira** [comment]
+1

**Comment by omayevskiy** [comment]
added support for 2017.3 with #191 , should also work with PyCharm.
Please close ticket if it works for you

**Comment by Epithumia** [comment]
Tested the built version on the Intellij repo, it's working, as far as I can tell.
