### ISSUE TITLE
2.1.4 not compatible with IntelliJ IDEA 2017.3.1

### ISSUE THREAD

**Issue by snooppy** [sonar-intellij-plugin/sonar-intellij-plugin#191]
**2.1.4 not compatible with IntelliJ IDEA 2017.3.1.**

IntelliJ IDEA 2017.3.1 (Ultimate Edition)
Build #IU-173.3942.27, built on December 11, 2017

JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-101-generic

**Comment by omayevskiy** [comment]
released 2.2.0: make compatible with 173.*
