### ISSUE TITLE
sonarLint and sonarqube show different check result

### ISSUE THREAD

**Issue by jasonwangnanjing** [sonar-intellij-plugin/sonar-intellij-plugin#193]
Hi,

I installed sonarLint plug-in on my intellij and configured it to connect to sonarqube server. So i assume all the checks within intellij will show the check result from server's rules.
But when i check the sonarLint result inside intellij, i saw difference between it and sonarqube server's issues.
I think they should be the same as local are checking with server's rules.

**Comment by vu-trong-the** [comment]
Hi, 
I have the same issue. Do we have any solution for this case?

**Comment by TobiasRath** [comment]
Hey,
I have this issue too. Any solutions?

**Comment by omayevskiy** [comment]
please post your issue to the sonarLint project: https://github.com/SonarSource/sonarlint-intellij
