### ISSUE TITLE
Use token as credential

### ISSUE THREAD

**Issue by opack** [sonar-intellij-plugin/sonar-intellij-plugin#202]
Hello !

I use Azure AD to log my users into SonarQube. Thus, they cannot input their credentials into the plugin.

I think a correct solution would be to allow the use of a token generated from the SQ interface.

What do you think of this ?

**Comment by omayevskiy** [comment]
good idea, can you provide a pool request?

**Comment by jsixface** [comment]
I am working on a pull request for adding Token to the server configuration. Will submit it soon.

**Comment by jsixface** [comment]
Can someone confirm if the PR is working for the API token

**Comment by omayevskiy** [comment]
yes will test next days
