### ISSUE TITLE
Errors displayed three times

### ISSUE THREAD

**Issue by jsixface** [sonar-intellij-plugin/sonar-intellij-plugin#212]
After running analysis, all the errors are displayed in the editor three times

![sonarqube-error](https://user-images.githubusercontent.com/2518805/46891572-496a6500-ce38-11e8-8108-0fdd31202dd6.png)

**Comment by jwenting** [comment]
yup, getting the same thing. If it shows any errors at all, which seems to be another problem lately.
More often than not it says it finds no issues, despite the server listing the project as having 15000 code smells and bugs (legacy code, don't you love it).

**Comment by faster13** [comment]
I have the same problem in Idea 182.4505.22.
