### ISSUE TITLE
IDEA 2018.3 Incompatible with the current IntelliJ IDEA version.

### ISSUE THREAD

**Issue by huangyaaa** [sonar-intellij-plugin/sonar-intellij-plugin#217]

**Comment by icecuber** [comment]
Like i wrote on issue #210 
on 2018.3 i can install only an old 2.1 version, upgrading from 2018.2 disable the latest 2.5 version

**Comment by huangyaaa** [comment]
> Like i wrote on issue #210
> on 2018.3 i can install only an old 2.1 version, upgrading from 2018.2 disable the latest 2.5 version

2.1 version works fine. i search plugins in marketplace then i only find the latest version 2.1, the [website](https://plugins.jetbrains.com/plugin/7238-sonarqube-community-plugin) provide the latest 2.5 version but not works fine. thanks

**Comment by eylonmalin** [comment]
Why this issue was closed ?
I want to use version 2.5 but can't use it with 2018.3
