### ISSUE TITLE
Unable to install plugin after update to IntelliJ IDEA 2018.3.1

### ISSUE THREAD

**Issue by zbynekvavros** [sonar-intellij-plugin/sonar-intellij-plugin#221]
Before the update everything was peachy. After the update plugin stopped working so quick google suggest to install 2.1.1-SNAPHOT. This is only compatible with builds 163.*. But current build is 183.

And 2.1.0 causes well known https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/issues/168.

IntelliJ IDEA 2018.3.1 (Ultimate Edition)
Build #IU-183.4588.61, built on December 4, 2018
Licensed to ################
Subscription is active until #################
JRE: 1.8.0_152-release-1343-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

Thanks for any pointers,
Zbynek

**Comment by copperleaf91** [comment]
Are there any plans to address this or known workarounds?

**Comment by omayevskiy** [comment]
vers 2.6.x supports 2018.3
please verify and close

**Comment by zbynekvavros** [comment]
What is the relation with downloads from JetBrains (https://plugins.jetbrains.com/plugin/7238-sonarqube-community-plugin) and from GitHub (https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/releases) ? I would expect the same versioning...

PS: 2.6.1 works fine!

**Comment by omayevskiy** [comment]
JetBrains (https://plugins.jetbrains.com/plugin/7238-sonarqube-community-plugin)
is the correct source, basically you should install the plugin from inside intellij

**Comment by zbynekvavros** [comment]
Aha I see, thanks for clarification!
