### ISSUE TITLE
Local analysis is not possible anymore

### ISSUE THREAD

**Issue by Vampire** [sonar-intellij-plugin/sonar-intellij-plugin#231]
Unfortunately it seems SS decided to finally deprecate and eventually kick all analysis modes besides `publish` which is for uploading the result to the SQ server, so latest after they drop the `preview` and `issues` modes, local analysis will probably not be possible anymore. :-(

Just wanted to document this here for others wondering and in case you didn't know already.

**Comment by omayevskiy** [comment]
:-(

**Comment by Vampire** [comment]
And it happened, I just upgraded to latest SQ version and since 7.9.1, local analysis possibility is gone. :-(
