### ISSUE TITLE
Metadata of 2.1.0

### ISSUE THREAD

**Issue by Vampire** [sonar-intellij-plugin/sonar-intellij-plugin#240]
2.1.0 in the plugin portal declares compatibility 2016.2+ which means it is suggested as plugin update if there is no newer matching and the installed one is no longer compatible with the new IJ version like always.

Please fix the metadata of 2.1.0 to not be suggested as update. Usual people don't look that closely and just press succeed.

**Comment by omayevskiy** [comment]
done

**Comment by Vampire** [comment]
Hm, and now the same for all other older versions. :-/

**Comment by Vampire** [comment]
Maybe you should let the latest version be minVersion+ so that no older versions are suggested on update and only if you find it incompatible, release a new version and then set the max version of the previous plugin.
