### ISSUE TITLE
All releases after 2.0.12 disappeared

### ISSUE THREAD

**Issue by hebus59** [sonar-intellij-plugin/sonar-intellij-plugin#241]
Hello,

I've upgraded my IntelliJ from 2018.3 to 2019.1.1.

IntelliJ tells me that an upgrade from 2.6.4 to 2.0.12 is available for this sonar plugin.
But this is a downgrade !

When I look at releases on GitHub, I can't see any release after 2.0.12...

Have they been deleted ?
Is there a problem on GitHub ?

Thanks in advance for your help,

Fabrice

**Comment by omayevskiy** [comment]
updated all older versions and replaced unlimited until version

**Comment by omayevskiy** [comment]
removed releases from github, this was confusing. Releases are uploaded to intellij plugins repository, not to github.
