### ISSUE TITLE
Cannot setup with sonarcloud

### ISSUE THREAD

**Issue by antonino-tocco** [sonar-intellij-plugin/sonar-intellij-plugin#242]
Hi all, I cannot setup sonarcloud.io as server for my project.
Can you help me?

**Comment by omayevskiy** [comment]
is not supported

**Comment by bonivan** [comment]
Looks like additional parameter "organization" should be passed to REST API call to be able to load projects from sonarcloud.io.

**Comment by vikasprogrammer** [comment]
Whats the URL you are using for sonarcloud?

**Comment by omayevskiy** [comment]
>Whats the URL you are using for sonarcloud?
https://sonarcloud.io

**Comment by omayevskiy** [comment]
>Hi all, I cannot setup sonarcloud.io as server for my project.

is possible now with version 2.8.0 after merging pull request from @bonivan 

for sonarcloud you additionally need to specify organization field in your sonar server config as described in the [README.md](https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/blob/master/README.md)
