### ISSUE TITLE
Cannot run SonarQube in IntelliJ 2019.3

### ISSUE THREAD

**Issue by FelixFly** [sonar-intellij-plugin/sonar-intellij-plugin#252]
Cannot run SonarQube in IntelliJ 2019.3

**Comment by omnipitous** [comment]
Came here to say this.. they really need to update the "This version works in all versions of IntelliJ" message on the page.. :(  I had 9 plugin incompatibilities when I upgraded a minute ago. 8/9 had new versions to handle this.. not SonarQube!
