### ISSUE TITLE
When running the new issues inspection without local analysis script no error happens

### ISSUE THREAD

**Issue by Vampire** [sonar-intellij-plugin/sonar-intellij-plugin#254]
When running the `SonarQube Issue SonarQube (new issues)` inspection, you need to have a local analysis script configured in the settings.

If no script is configured and you try to run that inspection, you are told that "there are ne new issues" immediately, which is not necessarily correct.

Instead it cannot be determined and an error should be shown if the inspection is invoked while no analysis script is configured.

**Comment by omayevskiy** [comment]
https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/pull/256

**Comment by omayevskiy** [comment]
2.8.3 released

**Comment by Vampire** [comment]
It is maybe still sub-optimal:
You get these two while I would only expect the second:
![grafik](https://user-images.githubusercontent.com/325196/77437424-f0508000-6de4-11ea-98c0-b08014e7a0b2.png)
Besidest that `enabled` should maybe be `executed`.
