### ISSUE TITLE
Plugin is not usable anymore with recent SQ version and many findings (slow and erroneous)

### ISSUE THREAD

**Issue by Vampire** [sonar-intellij-plugin/sonar-intellij-plugin#255]
I just upgraded our SQ instance from 7.5 to 8.1.0.
This upgrade includes, that SQ removed the concept of modules completely and only has projects and physical paths therein.

Because of that I needed to change the SonarQube resources for the single modules in our multi-project build from the single modules on SonarQube all to the project resources directly.

This means, when I now invoke the `SonarQube Issue SonarQube` inspection on a single file, the plugin first tries to download all unresolved issues for the whole project, which in our case means 43_225 issues.

This includes three problems.
1. it needs aaaaages to display issues for even one file, as always the issues for the whole project are downloaded
2. it downloads until page 20 is done and then when it tries to download page 21 (with a page size of 500) fails as you can only download the first 10_000 issues. After this page download failed, there is no error displayed, but it says that there are no issues found which is plainly wrong, an error should be shown instead
3. well, no issues can ever be displayed if you have more than 10_000, as they cannot be downloaded

- When downloading issues you need to make sure that you do not try to request more than 10_000 issues and if you do, you need to split the requests.
- Besides the 10_000 limit, it would also be a performance boost if you restrict further which issues are downloaded, as you can download issues more targeted. If you for example add parameter `componentKeys=com.example:project:path/to/src/main/java/com/example/my/package/MyClass.java`, you only get the issues for that exact file.

**Comment by omayevskiy** [comment]
I see your arguments, I see also another issue: a project with 43_225 issues
- nobody will ever fix 40k issues
- even you would be able to download and display all this issues and the IDE would display them, they are in no way usefully
- use only rules which are relevant to you
- analyze only source code which is relevant to you
- exclude irrelevant files from analysis, like generated code
- try to get down to 0 issues and keep the project clean from this day on (this will also speed up your build)

**Comment by omayevskiy** [comment]
>When downloading issues you need to make sure that you do not try to request more than 10_000 issues and if you do, you need to split the requests.

this was solved already, needs to be fixed again

**Comment by omayevskiy** [comment]
@Vampire please check https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/pull/257

**Comment by omayevskiy** [comment]
2.8.3 released

**Comment by Vampire** [comment]
Please reopen this and properly fix it.
Just hard limiting to 10_000 without the possibility to only download the issues of one module still means the plugin is not usable for big old projects that are now one big bunch in SonarQube.

Ok, let me shortly follow your advice:

> nobody will ever fix 40k issues

Agreed, but not under my control

> even you would be able to download and display all this issues and the IDE would display them, they are in no way usefully

Noone wants to download 40k issues and display them.
I want to display the issues of one class I'm currently working on and this is not possible.
You could restrict the query path-wise and thus only download and parse the relevant issues.
Currently you always just download all issues, parse them and then throw away what was not requested by scope.
This needs time to download all issues, it needs time to parse all issues and this repeatedly while you could simply only download the issues that are of interest for the selected scope.

> use only rules which are relevant to you

ok, done

> analyze only source code which is relevant to you

ok, done

> exclude irrelevant files from analysis, like generated code

oh, great, done

Now let's see what we got ... oh, still 43_225 issues :-(

Of course we did these steps already.
But this is a pretty big project with 2.3 million lines of code that grew over the last almost 20 years and most of the time people did not care enough about code quality.

These are the rules we want to follow and they are applied to the relevant code.
You are welcome to stop by for a day or two and fix all those issues to get down to 0 and then we will make sure we stay on 0.
In the meantime we can only follow the rule to not add new findings in new code and fix findings in old code when it is touched anyway.

Up to now this was not really a problem as the code is split in about 50 modules and as long as SonarQube supported the module concept, there was no issue at all.

Now that they forced one project as one big hunk, the amount is not handled properly by your plugin anymore. If I now request the issues for a file that is betwenn issue 10_001 and 43_225, the file will falsely be shown as having no issues by your plugin, simply because you only download the first 10k issues and ignore the rest.

So please, please, please, with sugar on top, make your plugin usable again and thereby also more performant saving downloading and parsing time, by only requesting the issues that are relevant for the selected scope.

**Comment by omayevskiy** [comment]
FYI I currently out of order due to missing workstation .
You could as already mentioned ignore non maintainable files and directories and exclude them from the analysis completely,  this save you also time to run the analysis on your CI build.
See e.g. https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/ for how to exclude.

**Comment by Vampire** [comment]
> You could as already mentioned ignore non maintainable files and directories and exclude them from the analysis completely, this save you also time to run the analysis on your CI build.
> See e.g. https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/ for how to exclude.

As mentioned already, this is done of course.
Only the necessary files are analysed with only the wanted rules.
This does not make the issues magically vanish.

This plugin in its current state remains unusable for old projects with many issues.
It now does not fail and downloads the first 10k issues, but all other issues are not accessible and it of course still wastes time to download 10k issues if you want the issues for a specific file.

I would still be great if you would reopen this issue and improve on this in the future, so that the plugin becomes usable and performant again.

**Comment by Vampire** [comment]
hello?

**Comment by omayevskiy** [comment]
@Vampire pong

Can u provide an example project u r talking about?
I would want to see the issue and think about what could be done based on the analysis scope.

**Comment by Vampire** [comment]
Unfortunately it is a closed source proprietary codebase, so no I cannot provide the project.
But as I said already multiple times.
The main issue is, that you request all issues of the project and then throw away what does not match the analysis scope instead of right away only requesting what the user wants to display.
If you have a project with 100 findings in 100 different files and you want to show issues for one of those files, you currently download all 100 findings, parse them and then throw away 99 of them as they do not match the analysis scope.
Instead you could right away just request the issues that are wanted as described above which would save download time, parsing time and also fix this issue.

**Comment by omayevskiy** [comment]
Can u find another project like this? Ideally on sonarcloud.io and source code in github

**Comment by Vampire** [comment]
Yes, there are several, just scroll through the featured projects, or the XL-sized projects and you easily find several.
For example https://github.com/TYPO3/TYPO3.CMS.
It has 12757 issues and thus exactly the same problems as our internal project.
You can only get the first 10000 issues and files with issues in the other 2757 will potentially show as good while there are issues and if you select a restricted scope like a single file, you still download all issues just to throw away 99.99% of them instead of up-front just requesting the issues belonging to the requested scope like a module or file or whatever.

**Comment by Vampire** [comment]
Any news?
Can you at least reopen the issue as I gave you examples?

**Comment by Vampire** [comment]
Hello?
