### ISSUE TITLE
Rider 2020.1

### ISSUE THREAD

**Issue by graffymichal** [sonar-intellij-plugin/sonar-intellij-plugin#262]
After successfull download SonarQube resources from sonarcloud, in SonarQube console all time shows message:
"Use Analyze -> Inspect Code to update Issues from SonarServer." and Inspect Code (tried module, solution all options) , Analyze Solution etc, the message still showind and in the Inspection Results have no SonarQube warnings, but on sonarcloud we have warnings... 
(C# .net core project) 
What can be wrong? Is it working or no?

**Comment by IhorKrupinEmpeek** [comment]
Same problem.
btw there's no "Analyze -> Inspect Code" tab in Rider as far as I can see.

**Comment by m2rt** [comment]
Same in Rider 2020.2

**Comment by davweiss** [comment]
Same in Rider 2020.3

**Comment by omayevskiy** [comment]
Does anybody knows a C# example project like:

https://github.com/scottenriquez/sonarcloud-travis-ci-csharp
https://sonarcloud.io/dashboard?id=scottenriquez_sonarcloud-travis-ci-csharp

my issue with the project above is, it has no SonarQube issues

**Comment by omayevskiy** [comment]
ok found one:

https://sonarcloud.io/dashboard?id=Automated-SecurityTesting-Demo
https://github.com/maartenderaedemaeker/Automated-SecurityTesting-Demo/tree/part1

**Comment by omayevskiy** [comment]
I was able to display the inspections for the project above using:
Rider 2020.3.2
SonarQube IntelliJ Community Plugin 2.9.7

I did:
Code -> Run Inspection by name -> typed "sonar" -> selected "SonarQube issues" (the one without "new issues")
and run for project

in the server settings, I set up:

host URL: https://sonarcloud.io/
organization: maartenderaedemaeker-github

and SecurityDemo is project key


my  output was:

INFO 19:39:28.215 > Downloading issues for SonarQube resource Automated-SecurityTesting-Demo:Automated-SecurityTesting-Demo:644BC1A0-7759-4E15-B38C-D7631B256E27
INFO 19:39:28.963 > Downloaded 77 issues in 00:00:748
INFO 19:39:28.963 > Creating index for SonarQube resource Automated-SecurityTesting-Demo:Automated-SecurityTesting-Demo:644BC1A0-7759-4E15-B38C-D7631B256E27
INFO 19:39:28.964 > Start processing 88 files and 77 issues with 8 threads
INFO 19:39:28.967 > 34 / 88 files processed
INFO 19:39:28.971 > 68 / 88 files processed
INFO 19:39:28.976 > Finished creating index with 54 issues for SonarQube resource Automated-SecurityTesting-Demo:Automated-SecurityTesting-Demo:644BC1A0-7759-4E15-B38C-D7631B256E27 in 00:00:013

![image](https://user-images.githubusercontent.com/3081911/104351783-7f628c00-550e-11eb-984b-c10c8c20c65f.png)

**Comment by omayevskiy** [comment]
@graffymichal, can you verify if it works for you and closes the issue if so?

**Comment by davweiss** [comment]
This works for me! Thank you
