### ISSUE TITLE
error with sonarqube server 

### ISSUE THREAD

**Issue by shiftilike** [sonar-intellij-plugin/sonar-intellij-plugin#272]
i use this plugins but found this error:
INFO 10:26:02.430 > Downloading issues for SonarQube resource eya-micro-service
ERROR 10:26:02.556 > Error 400 on http://**/api/issues/search?componentRoots=eya-micro-service&ps=-1&projectKeys=eya-micro-service&resolved=false : {"errors":[{"msg":"Page size must be between 1 and 500 (got -1)"}]}
INFO 10:26:02.557 > Downloaded 0 issues in 00:00:146

**Comment by omayevskiy** [comment]
see https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/issues/273#issuecomment-753452532
