### ISSUE TITLE
Compatibility with 2021.1

### ISSUE THREAD

**Issue by ErMaqui** [sonar-intellij-plugin/sonar-intellij-plugin#279]
Hi,

Is the plugin being updated for 2021.1? I've updated my IDE and apparently, version 2.9.7 are not compatible.

Thanks,

**Comment by rvajustin** [comment]
**bump**

**Comment by rvajustin** [comment]
Thanks for your hard work!

**Comment by ErMaqui** [comment]
Thanks!
