### ISSUE TITLE
Path to sonar-report.json with PROJECT_BASE_DIR does not work

### ISSUE THREAD

**Issue by Vampire** [sonar-intellij-plugin/sonar-intellij-plugin#71]
I have "$PROJECT_BASE_DIR/build/sonar/sonar-report.json" configured as sonar-report.json, but at the end of the analysis, it complains that it does not find the file where in the path it writes, all path separators (backslashes, it is Windoze here) that are part of PROJECT_BASE_DIR are removed.

**Comment by Sendami** [comment]
This is still happening, at least using intellij 15.0.1 version

**Comment by sn4pf1sh** [comment]
For me only mode=incremental works. Analysis and preview both are generating the FileNotFoundException. I found out that the .sonar directory is fully cleaned after analyzing. During analyzing the sonar-report.json file is where it should be.
